### ISSUE TITLE
Pianoroll (TTK)

### ISSUE THREAD

**Issue by TASLabz** [TASLabz/mkw-scripts#2]

**Comment by malleoz** [comment]
Current status:
- Ghosts now sync when loading state from before race inputs start
- Loading savestates repeatedly can lead to a desync. Not 100% sure yet what the exact cause is

**Comment by ximk** [comment]
Desyncing issues resolved in #10.

Ghost pianoroll is in development. This issue will close once that is complete.

**Comment by vabold** [comment]
Brave to assign this task to four people at once.
