### ISSUE TITLE
Modules not found on Mac

### ISSUE THREAD

**Issue by malleoz** [TASLabz/mkw-scripts#28]
We need to add a __init.py file to the Modules folder, and change all module imports to Modules.TTK_Lib for example. This is because in Dolphin, there is Windows-exclusive code which sets the Python paths.

**Comment by thatsslick** [comment]
PR to fix: https://github.com/TASLabz/mkw-scripts/pull/29

**Comment by malleoz** [comment]
Merged! Still need Dolphin component improved.
